### ISSUE TITLE
Figure out a proper YAML/JSON file format for knowledge store

### ISSUE THREAD

**Issue by ankurayadav** [arbrain/abrain#1]
Figure out a knowledge schema that is intuitive to understand and that can be easily made.
I think schema definition in form of a dialect of opencypher would be better as it is very intuitive and easy to understand.
But I am also thinking of something different like below.

Nodes: User, Region, Songs
Relationships: LIVES_IN, LITENS
User: Keys(username, location), Properties(age, sex)
Region: Keys(name)
Song: Keys(id, name, artist)

(Region)<-[LIVES_IN]-(User),
(User)-[LITENS]->(Song)

**Comment by ankurayadav** [comment]
Sample YAML file for knowledge graph schema.
```
Nodes:
    User:
        Properties:
            name: String, Indexed
            user_id: Integer, Unique
        Edges_out:
            LIVES_IN: Region
            LITENS: Songs
    Region:
        Properties:
            name: String, Indexed
            region_id: Integer, Unique
    Song:
        Properties:
            id: String, Unique
            name: String, Indexed
            artist: String, Indexed

Edges:
    LITENS:
        Properties:
            weight: Integer
```
